#     Copyright 2014-2015 Emiliano Mennucci
#
#     This file is part of VLAM.
# 
#     VLAM is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     VLAM is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with VLAM.  If not, see <http://www.gnu.org/licenses/>.

import os

Import('env')

scanner = env.CXXFile(target = 'grammar/scanner.cpp', source = 'grammar/scanner.ll')
parser = env.CXXFile(target = 'grammar/parser.cpp', source = 'grammar/parser.yy', YACCFLAGS='-d')
files = Glob('*.cpp') + Glob('util/*.cpp')

libvlam = env.Library('libvlam', files + [scanner] + [parser[0]])

Alias('libvlam', libvlam)

Return('libvlam')
